services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: raid_db
      POSTGRES_USER: raid_user
      POSTGRES_PASSWORD: raid_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - DB_NAME=raid_db
      - DB_USER=raid_user
      - DB_PASSWORD=raid_pass
      - DB_HOST=db
      - DB_PORT=5432
      - AI_API_KEY=AIzaSyAJYEmM4pDiUWvJAw90nzAgEb81LfH9KcE
    depends_on:
      - db

volumes:
  postgres_data:
