# Generated by Django 4.2.23 on 2025-06-20 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('onboarded_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('authorized_users', models.ManyToManyField(blank=True, related_name='accessible_clients', to=settings.AUTH_USER_MODEL)),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('incident_manager', 'Incident Manager'), ('incident_responder', 'Incident Responder'), ('client', 'Client'), ('lead_responder', 'Lead Responder')], max_length=20)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('ticket_raised', 'Ticket Raised'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('analysis_complete', 'Analysis Complete'), ('report_draft', 'Report Draft'), ('report_final', 'Report Final'), ('closed', 'Closed')], default='ticket_raised', max_length=20)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('client_can_view_analysis', models.BooleanField(default=False)),
                ('client_can_view_reports', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.client')),
                ('incident_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_incidents', to=settings.AUTH_USER_MODEL)),
                ('lead_responder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_incidents', to=settings.AUTH_USER_MODEL)),
                ('responders', models.ManyToManyField(blank=True, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
