# Generated by Django 4.2.23 on 2025-06-20 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artefact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('artefact_type', models.CharField(choices=[('evtx', 'Windows Event Log (EVTX)'), ('pcap', 'Packet Capture (PCAP)'), ('sysmon', 'Sysmon Logs'), ('firewall', 'Firewall Logs'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='artefacts/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parsed', models.BooleanField(default=False)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artefacts', to='core.incident')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_index', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('artefact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.artefact')),
            ],
        ),
        migrations.CreateModel(
            name='ArtefactNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artefact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.artefact')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_in_notes', to='core.logrecord')),
            ],
        ),
    ]
