# Generated by Django 4.2.23 on 2025-06-20 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_artefact_logrecord_artefactnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefact',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='working_artefacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_artefacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
