# Generated by Django 4.2.23 on 2025-06-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_artefact_assigned_to_alter_artefact_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logrecord',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='logrecord',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='artefact_type',
            field=models.CharField(choices=[('evtx', 'Windows Event Log (EVTX)'), ('pcap', 'Packet Capture (PCAP)'), ('log', 'Logs Files'), ('firewall', 'Firewall Logs'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
