# Generated by Django 4.2.23 on 2025-06-23 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_remove_logrecord_metadata_remove_logrecord_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogicUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('pattern', models.TextField()),
                ('evaluate', models.CharField(choices=[('contains', 'Contains'), ('regex', 'Regex')], max_length=10)),
                ('negate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('reference', models.TextField(blank=True)),
                ('condition_json', models.JSONField(help_text='Boolean logic tree using logic unit IDs')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logics', models.ManyToManyField(blank=True, to='analysis.logicunit')),
            ],
        ),
        migrations.CreateModel(
            name='RuleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RuleMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('artefact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.artefact')),
                ('log_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.logrecord')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='analysis.rule')),
            ],
        ),
        migrations.AddField(
            model_name='rule',
            name='tags',
            field=models.ManyToManyField(blank=True, to='analysis.ruletag'),
        ),
    ]
