# Generated by Django 4.2.23 on 2025-06-24 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_remove_logrecord_metadata_remove_logrecord_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogicUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pattern', models.TextField()),
                ('method', models.CharField(choices=[('contains', 'Contains'), ('regex', 'Regex')], max_length=10)),
                ('negate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MitreTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boolean_expression', models.TextField(help_text='Use logic aliases like: (L1 and L2) or not L3. L1 refers to the 1st logic in the list.')),
                ('logics', models.ManyToManyField(blank=True, related_name='rules', to='analysis.logicunit')),
                ('mitre_techniques', models.ManyToManyField(blank=True, to='analysis.mitretechnique')),
            ],
        ),
        migrations.CreateModel(
            name='RuleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RuleMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('artefact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_matches', to='core.artefact')),
                ('log_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_matches', to='core.logrecord')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='analysis.rule')),
            ],
        ),
        migrations.AddField(
            model_name='rule',
            name='tags',
            field=models.ManyToManyField(blank=True, to='analysis.ruletag'),
        ),
        migrations.CreateModel(
            name='LogicEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField()),
                ('logic_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.logicunit')),
                ('rule_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logic_evaluations', to='analysis.rulematch')),
            ],
        ),
    ]
