# Generated by Django 4.2.23 on 2025-07-06 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_logrecord_metadata_remove_logrecord_timestamp_and_more'),
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artefact_type', models.CharField(max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField()),
                ('narrative', models.TextField()),
                ('highlights', models.JSONField(default=list)),
                ('references', models.JSONField(default=list)),
                ('prompt_used', models.TextField()),
                ('raw_response', models.JSONField(default=dict)),
                ('artefact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_results', to='core.artefact')),
            ],
        ),
    ]
