# Generated by Django 4.2.23 on 2025-07-06 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_logrecord_metadata_remove_logrecord_timestamp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis', '0002_aianalysisresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField()),
                ('hypotheses', models.JSONField(default=list)),
                ('recommended_actions', models.JSONField(default=list)),
                ('per_artefact_context', models.JSONField(default=dict)),
                ('prompt_used', models.TextField()),
                ('raw_response', models.JSONField(default=dict)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_incident_results', to='core.incident')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentHypothesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('mitre_techniques', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hypotheses_list', to='analysis.incidentanalysisresult')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_actions', to=settings.AUTH_USER_MODEL)),
                ('hypothesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='analysis.incidenthypothesis')),
            ],
        ),
    ]
