# Generated by Django 4.2.23 on 2025-07-06 21:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_incidentanalysisresult_incidenthypothesis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentaction',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='incidentaction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='incidentaction',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='incidentanalysisresult',
            name='hypotheses',
        ),
        migrations.RemoveField(
            model_name='incidentanalysisresult',
            name='per_artefact_context',
        ),
        migrations.RemoveField(
            model_name='incidentanalysisresult',
            name='recommended_actions',
        ),
        migrations.RemoveField(
            model_name='incidenthypothesis',
            name='analysis_result',
        ),
        migrations.RemoveField(
            model_name='incidenthypothesis',
            name='created_at',
        ),
        migrations.AddField(
            model_name='incidenthypothesis',
            name='analysis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hypotheses', to='analysis.incidentanalysisresult'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidenthypothesis',
            name='artefacts',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='incidentanalysisresult',
            name='generated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
