# Generated by Django 4.2.23 on 2025-07-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_remove_incidentaction_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentanalysisresult',
            name='graph',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
