# Generated by Django 4.2.23 on 2025-07-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_incidentanalysisresult_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentanalysisresult',
            name='traceable_sankey',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
