# Generated by Django 4.2.23 on 2025-07-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_incidentanalysisresult_traceable_sankey'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentanalysisresult',
            name='gaps',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='incidentanalysisresult',
            name='workflows',
            field=models.JSONField(default=list),
        ),
    ]
