# Generated by Django 4.2.23 on 2025-07-19 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_incidentanalysisresult_gaps_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentanalysisresult',
            old_name='graph',
            new_name='graphs',
        ),
        migrations.RemoveField(
            model_name='incidentanalysisresult',
            name='traceable_sankey',
        ),
    ]
